<?php

// Constants
	const USERNAME	= "ENTER NETATMO USERNAME";
	const PASSWORD	= "ENTER NETATMO PASSWORT";
	const APPID	= "ENTER NETATMO APPID";
	const APPSECRET = "ENTER NETATMO APPSECRET";
	const LANGUAGE  = "ENTER LANGUAGE"; // de / en / es

?>
